# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(default='FileUpload/None/No-File.txt', upload_to='FileUpload/')),
            ],
        ),
    ]
