# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20160810_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphoto',
            name='doc',
            field=models.FileField(default='Doc/None/No-doc.pdf', upload_to='Doc/'),
        ),
        migrations.AlterField(
            model_name='myphoto',
            name='image',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/'),
        ),
    ]
